import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Web3AuthProvider from '@/context/Web3AuthContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Web3AuthProvider>
        <body className={inter.className}>
          {children}
        </body>
      </Web3AuthProvider>
    </html>
  );
}
